[General]
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
dns-server = https://dns.alidns.com/dns-query, https://doh.pub/dns-query
fallback-dns-server = system
ipv6 = false
prefer-ipv6 = false
dns-fallback-system = false
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = false
update-url = https://raw.githubusercontent.com/ionony/config/master/final_direct.conf



[Proxy Group]

自动选择 = select, ALL, 香港节点, 日本节点, 美国节点
ALL = url-test, url=http://www.gstatic.com/generate_204, interval=600, tolerance=100, timeout=5, policy-regex-filter=.*
香港节点 = url-test, url=http://www.gstatic.com/generate_204, interval=600, tolerance=100, timeout=5, policy-regex-filter=HK|Hongkong|香港|港
日本节点 = url-test, url=http://www.gstatic.com/generate_204, interval=600, tolerance=100, timeout=5, policy-regex-filter=JP|Japan|日本|本
美国节点 = url-test, url=http://www.gstatic.com/generate_204, interval=600, tolerance=100, timeout=5, policy-regex-filter=US|United States|美国|美





[Rule]
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Advertising/Advertising.list,REJECT
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/ChinaMaxNoIP/ChinaMaxNoIP_Domain.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/ChinaMaxNoIP/ChinaMaxNoIP.list,DIRECT
DOMAIN-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Global/Global_Domain.list,自动选择
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Global/Global.list,自动选择
GEOIP,CN,DIRECT
FINAL,DIRECT






