[General]
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
dns-server = https://dns.alidns.com/dns-query, https://doh.pub/dns-query
fallback-dns-server = system
ipv6 = false
prefer-ipv6 = false
dns-fallback-system = false
dns-direct-system = false
icmp-auto-reply = true
always-reject-url-rewrite = false
private-ip-answer = false
update-url = https://raw.githubusercontent.com/ionony/config/master/final_proxy.conf



[Proxy Group]

自动选择 = select, ALL, 香港节点, 台湾节点, 日本节点, 美国节点, 新加坡节点

香港节点 = select, policy-regex-filter=(?i)HK|Hongkong|香港|港
台湾节点 = select, policy-regex-filter=(?i)TW|Taiwan|台湾|台
日本节点 = select, policy-regex-filter=(?i)JP|Japan|日本
美国节点 = select, policy-regex-filter=(?i)US|United States|美国|美
新加坡节点 = select, policy-regex-filter=(?i)SG|Singapore|新加坡

ALL = url-test, policy-regex-filter=.*, url=http://www.gstatic.com/generate_204, interval=300, tolerance=50, timeout=3



[Rule]
RULE-SET,https://yfamilys.com/rule/ADLite.list,REJECT-TINYGIF
RULE-SET,https://yfamilys.com/rule/ChinaNoMedia.list,DIRECT
GEOIP,CN,DIRECT
FINAL,自动选择
